### ISSUE TITLE
Stuck after signing up

### ISSUE THREAD

**Issue by AnkitKumarSingh11** [parthpanchal123/Code-snipps#1]
The app usually stuck when you signup for the first time using email and password. But when you login, it works totally fine. I tried it twice but still got the same result.

**Comment by parthpanchal123** [comment]
Hey @AnkitAvi11 , thanks for pointing that out . I will soon look into whats the issue !

**Comment by parthpanchal123** [comment]
@AnkitAvi11 The issue seems to be fixed.

**Comment by AnkitKumarSingh11** [comment]
> @AnkitAvi11 The issue seems to be fixed. 

Yes now it's working totally fine ☺️

**Comment by parthpanchal123** [comment]
Do :star: the repo :smile:
